/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts.kasir;

//import static java.lang.String.format;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Faychan
 */
public class form extends javax.swing.JFrame {

    /**
     * Creates new form formsis
     */
    public form() {
        initComponents();
        setDate(); setTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        ltime = new javax.swing.JLabel();
        ldate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bed = new javax.swing.JButton();
        bsa = new javax.swing.JButton();
        bdel = new javax.swing.JButton();
        bcle = new javax.swing.JButton();
        bre = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        b8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lto = new javax.swing.JLabel();
        lto1 = new javax.swing.JLabel();
        b7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setLayout(null);

        ltime.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        ltime.setText("Time:");
        jPanel1.add(ltime);
        ltime.setBounds(620, 50, 254, 28);

        ldate.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        ldate.setText("Date:");
        jPanel1.add(ldate);
        ldate.setBounds(620, 20, 254, 28);

        jLabel10.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        jLabel10.setText("Rheinisch-Westfälische Technische Hochschule Aachen");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 20, 560, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 860, 90);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setToolTipText("ah");
        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        jLabel1.setText("Cashier 1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 0, 160, 40);
        jPanel2.add(tf1);
        tf1.setBounds(10, 70, 170, 29);
        jPanel2.add(tf3);
        tf3.setBounds(10, 190, 164, 29);

        jLabel7.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        jLabel7.setText("ID Barang");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 40, 100, 20);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 51));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSeparator1.setMinimumSize(new java.awt.Dimension(230, 50));
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 30, 230, 10);

        jLabel8.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        jLabel8.setText("Nama Barang");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 100, 130, 30);

        jLabel9.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        jLabel9.setText("Jumlah");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 160, 130, 30);
        jPanel2.add(tf2);
        tf2.setBounds(10, 130, 164, 29);

        tf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf4ActionPerformed(evt);
            }
        });
        jPanel2.add(tf4);
        tf4.setBounds(10, 250, 164, 30);

        jLabel5.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        jLabel5.setText("Harga Barang");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 220, 170, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 100, 220, 360);
        jPanel2.getAccessibleContext().setAccessibleName("");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        bed.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        bed.setText("EDIT");
        bed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedActionPerformed(evt);
            }
        });
        jPanel3.add(bed);
        bed.setBounds(10, 100, 120, 40);

        bsa.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        bsa.setText("SAVE");
        bsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaActionPerformed(evt);
            }
        });
        jPanel3.add(bsa);
        bsa.setBounds(10, 150, 120, 40);

        bdel.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        bdel.setText("DELETE");
        bdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdelActionPerformed(evt);
            }
        });
        jPanel3.add(bdel);
        bdel.setBounds(10, 250, 120, 40);

        bcle.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        bcle.setText("CLEAR");
        bcle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcleActionPerformed(evt);
            }
        });
        jPanel3.add(bcle);
        bcle.setBounds(10, 200, 120, 40);

        bre.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        bre.setText("REFRESH");
        bre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breActionPerformed(evt);
            }
        });
        jPanel3.add(bre);
        bre.setBounds(10, 50, 120, 40);

        b6.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        b6.setText("PROMO");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel3.add(b6);
        b6.setBounds(10, 300, 120, 40);

        jLabel2.setFont(new java.awt.Font("Castellar", 3, 24)); // NOI18N
        jLabel2.setText("ACTION");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 10, 120, 30);

        b8.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        b8.setText("PRINT");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel3.add(b8);
        b8.setBounds(10, 350, 120, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(720, 100, 150, 410);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID_Barang", "Nama Barang", "Jumlah Barang", "Harga Barang", "Total Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb1);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(10, 110, 440, 230);

        jPanel5.setBackground(new java.awt.Color(255, 255, 153));
        jPanel5.setLayout(null);

        jLabel4.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        jLabel4.setText("Total:");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(10, 10, 60, 18);

        lto.setFont(new java.awt.Font("Geometr415 Blk BT", 1, 36)); // NOI18N
        lto.setText("Rp");
        jPanel5.add(lto);
        lto.setBounds(90, 10, 50, 60);

        lto1.setFont(new java.awt.Font("Geometr415 Blk BT", 1, 36)); // NOI18N
        lto1.setText("0");
        jPanel5.add(lto1);
        lto1.setBounds(140, 10, 240, 70);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(10, 10, 440, 90);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(250, 100, 460, 360);

        b7.setFont(new java.awt.Font("Engravers MT", 0, 18)); // NOI18N
        b7.setText("EXIT TRANSACTION");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7);
        b7.setBounds(0, 470, 710, 40);

        setSize(new java.awt.Dimension(896, 555));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bcleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcleActionPerformed
        tf1.setText("");
        tf2.setText("");
        tf3.setText("");
        tf4.setText("");
    }//GEN-LAST:event_bcleActionPerformed

    private void bsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaActionPerformed
        if("".equals(tf1.getText()) || "".equals(tf2.getText()) ||"".equals(tf3.getText()) 
                || "".equals(tf4.getText())){
            JOptionPane.showMessageDialog(this, "Please, Fill Data", "Error", JOptionPane.WARNING_MESSAGE);           
        } else {
                int ada = Integer.parseInt(tf3.getText());
                int ad = Integer.parseInt(tf4.getText());
                int tot = Integer.parseInt(lto1.getText());
                int a = (ada*ad)+tot;
                String ado = Integer.toString(a);
            String SQL = "INSERT INTO kasir (id, item_name, item_amount, item_price, total_price)" 
                    + "VALUES ('"+tf1.getText()+"','"+tf2.getText()+"', '"
                    +tf3.getText()+"','" +tf4.getText()+"','" +ado+"')";
            int status = connectDB.execute(SQL);
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Added Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                lto1.setText(ado); 
            } else {
                JOptionPane.showMessageDialog(this, "Failed to Add", "Error", JOptionPane.WARNING_MESSAGE);           
            }
        }
            
    }//GEN-LAST:event_bsaActionPerformed

    private void bdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdelActionPerformed
        int row = tb1.getSelectedRow();
        if (row != -1){
            String id = tb1.getValueAt(row, 0).toString();
            String SQL = "DELETE FROM kasir WHERE id='"+id+"'";
            int status = connectDB.execute(SQL);
            if (status==1){
                JOptionPane.showMessageDialog(this, "Data Erased Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);           
                int ada = Integer.parseInt((String) tb1.getValueAt(row, 2));
                int ad = Integer.parseInt((String) tb1.getValueAt(row, 3));
                int tot = Integer.parseInt(lto1.getText());
                int a = tot-(ada*ad);
                String ado = Integer.toString(a);
                lto1.setText(ado);
            }else {
                JOptionPane.showMessageDialog(this, "Data Failed to Erase", "Error", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please, Select the Row First", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bdelActionPerformed

    private void breActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breActionPerformed
        selectData();
    }//GEN-LAST:event_breActionPerformed

    private void bedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedActionPerformed
        if("".equals(tf1.getText()) || "".equals(tf2.getText())
                ||"".equals(tf3.getText()) || "".equals(tf4.getText())){
            JOptionPane.showMessageDialog(this, "Please, Fill Data", "Error", JOptionPane.WARNING_MESSAGE);           
        } else {
            int ada = Integer.parseInt(tf3.getText());
            int tot = Integer.parseInt(lto1.getText());
            int ad = Integer.parseInt(tf4.getText());
            int a = (ada*ad)+tot;
            String ado = Integer.toString(a);
                
            int row = tb1.getSelectedRow();
            String id = tb1.getValueAt(row,0).toString();
            String SQL = "UPDATE kasir SET `id`='"+tf1.getText()
                    + "',`ItemName`='"+tf2.getText()
                    + "',`ItemAmount`='"+tf3.getText()
                    + "',`ItemPrice`='"+tf4.getText()
                    + "',`TotalPrice`='"+ado
                    +"' WHERE id="+id;
            int status = connectDB.execute(SQL);
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Edited Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to Add", "Error", JOptionPane.WARNING_MESSAGE);           
            }
        }
    }//GEN-LAST:event_bedActionPerformed

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        int row = tb1.getSelectedRow();
        
        if(row != -1){
            tf1.setText(tb1.getValueAt(row, 0).toString());
            tf2.setText(tb1.getValueAt(row, 1).toString());            
            tf3.setText(tb1.getValueAt(row, 2).toString());
            tf4.setText(tb1.getValueAt(row, 3).toString());
            int nah = Integer.parseInt(lto1.getText()); 
            int no = Integer.parseInt(tb1.getValueAt(row, 5).toString());
            lto1.setText(Integer.toString(nah-no));
        }
    }//GEN-LAST:event_tb1MouseClicked

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        String str = JOptionPane.showInputDialog(null, "INPUT PROMO CODE:", "Aachen Book Store",0);
        int disc = 70/100;
        if(str=="Aacher1292"){
            int ah = Integer.parseInt(lto1.getText());
            int an = ah*disc;
            lto1.setText(Integer.toString(disc));
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void tf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf4ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        String SQL = "DELETE FROM kasir";
        int status = connectDB.execute(SQL);
        this.dispose();
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton bcle;
    private javax.swing.JButton bdel;
    private javax.swing.JButton bed;
    private javax.swing.JButton bre;
    private javax.swing.JButton bsa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel ldate;
    private javax.swing.JLabel ltime;
    private javax.swing.JLabel lto;
    private javax.swing.JLabel lto1;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String C[] = {"id", "ItemName", "ItemAmount", "ItemPrice","TotalPrice"};
        DefaultTableModel dtm = new DefaultTableModel(null, C);
        String SQL = "SELECT * FROM kasir";
        ResultSet rs= connectDB.executeQuery(SQL);
        
        try {
            while(rs.next()) {
                String id = rs.getString(1);
                String ItemName = rs.getString(2);
                String ItemAmount = rs.getString(3);
                String ItemPrice = rs.getString(4);
                String TotalPrice = rs.getString(5);
                String data[] = {id, ItemName, ItemAmount, ItemPrice,TotalPrice};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(form.class.getName()).log(Level.SEVERE, null, ex);
        } tb1.setModel(dtm);
    }
public void setDate(){
    java.util.Date now = new java.util.Date();
    java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
    ldate.setText(kal.format(now));
    }

public void setTime(){
    ActionListener taskPerformer = new ActionListener(){
        public void actionPerformed(ActionEvent evt){
                String nolh = "";
                String nolm = "";
                String nols = "";
                
                
                Date dt = new Date();
                int vh = dt.getHours();
                int vm = dt.getMinutes();
                int vs = dt.getSeconds();
                
                if (vh<=9){
                    nolh = "0";
                } if (vm <= 9) {
                    nolm = "0";
                } if (vs <= 9){
                    nols = "0";
                }
               
                
                String h = nolh + Integer.toString(vh);
                String m = nolm + Integer.toString(vm);
                String s = nols + Integer.toString(vs);
                ltime.setText(h+":"+m+":"+s);
            }
        };
    new Timer(100, taskPerformer).start();
}
}


